services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22
    working_dir: /workspace
    command: sleep infinity
    volumes:
      - ..:/workspace
      - node-modules:/workspace/node_modules
    ports:
      - 3000:3000
      - 8000:8000

  mysql:
    image: mysql:8.4.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d

volumes:
  node-modules:
  mysql-data:
